apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cmpx575/rendered-manifests-pattern.git
    targetRevision: production
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
