apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.16.0
    helm.sh/chart: external-secrets-0.16.0
    servicebinding.io/controller: "true"
  name: external-secrets-servicebindings
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - pushsecrets
  verbs:
  - get
  - list
  - watch
