apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oci-vault-test
  namespace: external-secrets
spec:
  refreshInterval: 1h
  clusterSecretStoreRef:
    name: oci-vault
  data:
    - secretKey: oci-vault-test
      remoteRef:
        key: OCI_VAULT_TEST
