apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      compartment: production
      encryptionKey: production
      region: production
      vault: production
