apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      compartment: compartmentPlaceholder
      encryptionKey: encryptionKeyPlaceholder
      principalType: InstancePrincipal
      region: regionPlaceholder
      vault: vaultPlaceholder
