apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      compartment: staging
      encryptionKey: staging
      region: staging
      vault: staging
