---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.16.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
