apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      compartment: fake-compartment
      encryptionKey: fake-encryption-key
      region: fake-region
      vault: fake-vault
