apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-fake
