apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/cmpx575/rendered-manifests-pattern.git
    targetRevision: main
    path: argocd/base
    kustomize:
      patches:
        - target:
            kind: Application
            namespace: argocd
          patch: |-
            - op: replace
              path: /spec/source/targetRevision
              value: staging

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
