apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cmpx575/rendered-manifests-pattern.git
    targetRevision: staging
    # path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
