---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/refs/tags/v0.16.0/deploy/crds/bundle.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
